### ISSUE TITLE
Please provide a full working demo

### ISSUE THREAD

**Issue by digitalit** [dreamonkey/quasar-app-extension-meta#3]
Hi,
I'm trying to get this working but i get 

`[vue-router] Failed to resolve async component default: TypeError: Object(...) is not a function
/logga-in -> error during render
/app/node_modules/@dreamonkey/quasar-app-extension-meta/dist/exports.js:1
export * from "./mixins/meta";`

**Comment by IlCallo** [comment]
Can you provide a repro? Or at least enough context info to reproduce.
It works for us on different OS and machines

**Comment by digitalit** [comment]
I'm afraid o cant share the repo since it's my customers production. I have made my own solution: https://forum.quasar-framework.org/topic/6235/meta-plugin-dynamic-properties/7

That is pretty bloated and probably far from correct. I'm super excited by your extension but i would be so happy if i had an plain Quasar install demo with your extension implemented so i can figure out what to remove, what to change and so on.

I'm sure your extension work flawless once i do it right but my lack of skills prevents me from figure this out just based on chunks of instruction codes.

I'm sorry for this.
Best regards
/Peter

**Comment by IlCallo** [comment]
@digitalit from your error text, it seems the problem is not related to how you use the AE, but to something else in your project.
Have you tried creating a brand new Quasar project and apply the AE? It will take you 2 minutes and help you understand how it's meant to be used. Then if it still doesn't work, I can take a look at that trial repo and help you fix it. That's what a **repro** is, a minimal repo with reproducible error on your side, not your current project repo :)

**Comment by digitalit** [comment]
@IlCallo thank you.

I will try that approach.

**Comment by IlCallo** [comment]
Closing for lack of response, hope you found a solution to your problem!
